### ISSUE TITLE
Invalid response type

### ISSUE THREAD

**Issue by cyperus** [aleksei0807/react-images-uploader#11]
```
{  message:'invalid response type',
    response:{
        code:0,
        path:'https:///admin/667777.jpg'
  }, 
    fileName:"ImagesUploader"}
```
So, what is the valid response type and how to display the error message? Thanks.

**Comment by aleksei0807** [comment]
as you can see at https://github.com/aleksei0807/react-images-uploader/blob/master/src/index.jsx#L316 valid response type is Array or string

**Comment by vitalyliber** [comment]
@aleksei0807 Can I send additional information in response? For example id of image.

**Comment by vitalyliber** [comment]
I expected a behaviour as { image_urls: [{'link': 'https://...', id: 1}].

**Comment by kirillDanshin** [comment]
@vitalyliber please open new issue for this feature and we'll implement it. thanks.

anyway, this issue seems to be resolved.
