### ISSUE TITLE
Set Header, cors to request

### ISSUE THREAD

**Issue by dungvan** [aleksei0807/react-images-uploader#28]
I need to set the header with Authorization and Cors in the request, send it to my server and get response, i think this project is good, but some thing like this if it missing, it need to update in next version. Or if has another way to resolve this problem please support me, thank you!

**Comment by OakAndAspen** [comment]
I have the same problem, the request can't handle the Authorization header and never send the POST request, only the OPTIONS request. Sorry but I can't use this tool without authentication.

**Comment by JimishF** [comment]
Any solutions?

**Comment by JimishF** [comment]
'https://github.com/aleksei0807/react-images-uploader/blob/fa9b8afa07a73aec40078581a42b1029f762f61e/lib/index.js#L348

 `credentials:'include'` This has to be configurable.
