### ISSUE TITLE
Loopback

### ISSUE THREAD

**Issue by ssageghi** [aleksei0807/react-images-uploader#3]
Hi
how we can do this in loopback server?

**Comment by aleksei0807** [comment]
hi,
what exactly you mean by loopback server?

**Comment by ssageghi** [comment]
I used Loopback for my server 
and this is link to the website [https://loopback.io/](url)

**Comment by gnyani** [comment]
Hi,
How can we post the image to a backend spring boot service ? Can we also pass a message along with the image to the server?

**Comment by jediofthecode** [comment]
@gnyani You can post the data as base64, and format the JSON however you want to post to your server. If you require I can submit an example of how I am doing this.
